version: "3.3"

services:
  smarthome-db:
    image: mysql:5.6
    ports:
      - "6644:3306"
    environment:
      MYSQL_DATABASE: 'smarthomedb'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'root'
    volumes:
      - ./data.sql:/docker-entrypoint-initdb.d/0_init.sql
